package objects.behaviour;

import java.util.ArrayList;

import framework.Tile;
import objects.Cell;

// in this behaviour the cell scours its surroundings for 
public class HuntBehaviour extends MoveBehaviour {

	@Override
	public void execute(Cell c) {

		ArrayList<Tile> moves = c.getMoveSet();

		// first search for other cells in area
		scour(moves);
		// if found, check if you can eat/beat them
		// if so, check if they are far or close
		// if far, approach
		// if close, eat
		// if not found, then just move (move behaviour)
		moveAnywhere(c);
		
		/*
		ArrayList<Tile> moves = c.getMoveSet();
		
		// always move right (DEBUG)
		Tile destination = moves.get(2); // 2 is right of current pos
		
		
		moveTo(destination,c);
		*/
	}
	
	// returns true if the move generated by this behaviour is possible
	@Override
	public boolean isPossible(Cell c) {
		return c.properties.currentEnergy > 1;
	}
	
	// scours surrounding searching for tiles that holds a cell
	public Tile scour(ArrayList<Tile> tiles){
		ArrayList<Tile> targets = new ArrayList<Tile>();
		
		// if found, see if it can eat/beat any of those cells
		return chooseTarget(targets);
	}
	
	// selects a target from a list of targets that it can eat/beat
	public Tile chooseTarget(ArrayList<Tile> targets){
		Tile target = null;
		return target;
	}
}