package objects.behaviour;

import java.util.ArrayList;

import framework.Tile;
import objects.Cell;

public class MoveRightBehaviour extends Behaviour {

	@Override
	public void execute(Cell c) {

		ArrayList<Tile> moves = c.getMoveSet();
		Tile destination = moves.get(2);
		c.moveTo(destination);
	}
	
	// returns true if the move generated by this behaviour is possible
	public boolean isPossible(Cell c) {

		return c.properties.currentEnergy > 1;
	}
}